import xml.etree.ElementTree as ET
import os

TRANSLATIONS = {
    "欢迎使用 SimpleKaruzi": "Welcome to SimpleKaruzi",
    "简介": "Introduction",
    "这是一个专门用于简化 OpenCore EFI 制作流程的工具，通过自动化核心设置步骤并提供标准化配置，旨在减少手动操作的工作量，同时确保黑苹果折腾过程中的准确性。": "This is a tool specifically designed to simplify the OpenCore EFI creation process. By automating core setup steps and providing standardized configurations, it aims to reduce manual workload while ensuring accuracy during your Hackintosh journey.",
    "主要功能": "Key Features",
    "自动检测硬件配置 (CPU, GPU, 主板, 声卡, 网卡等)": "Automatically detect hardware configuration (CPU, GPU, Motherboard, Audio, Network, etc.)",
    "根据硬件生成定制化的 OpenCore config.plist": "Generate customized OpenCore config.plist based on hardware",
    "自动选择并下载所需的 Kexts 驱动": "Automatically select and download required Kexts drivers",
    "自动应用 ACPI 补丁 (SSDT)": "Automatically apply ACPI patches (SSDT)",
    "支持一键下载最新版 OpenCore 和 Kexts": "Support one-click download of the latest OpenCore and Kexts",
    "内置 Config 编辑器，方便微调": "Built-in Config Editor for fine-tuning",
    "使用步骤": "Usage Steps",
    "1. 在“硬件报告”页面导入或生成硬件报告": "1. Import or generate a hardware report on the \"Hardware Report\" page",
    "2. 在“兼容性”页面检查硬件兼容性": "2. Check hardware compatibility on the \"Compatibility\" page",
    "3. 在“配置”页面选择目标 macOS 版本和机型": "3. Select target macOS version and model on the \"Configuration\" page",
    "4. 在“构建”页面点击“开始构建”生成 EFI": "4. Click \"Start Build\" on the \"Build\" page to generate EFI",
    "免责声明": "Disclaimer",
    "本工具生成的 EFI 仅供参考，不保证 100% 完美驱动所有硬件。<br>在使用前，请务必备份您的重要数据。作者不对因使用本工具导致的任何数据丢失或硬件损坏负责。<br>黑苹果安装涉及风险，建议在有一定基础的情况下进行。": "The EFI generated by this tool is for reference only and does not guarantee 100% perfect driver support for all hardware.<br>Please backup your important data before use. The author is not responsible for any data loss or hardware damage caused by using this tool.<br>Hackintosh installation involves risks; it is recommended to proceed with some basic knowledge.",
    "正在获取公告...": "Fetching announcements...",
    "公告": "Announcement",
    "OCLP-Mod III - 现已支持 macOS Tahoe 26！": "OCLP-Mod III - Now Supports macOS Tahoe 26!",
    "期待已久的OCLP-Mod 3.x.x 版本已经发布，为社区带来了<b>对macOS Tahoe 26的初始支持</b>！<br><br>": "The long-awaited OCLP-Mod 3.x.x has been released, bringing <b>initial support for macOS Tahoe 26</b> to the community!<br><br>",
    "<b>请注意：</b><br>": "<b>Please Note:</b><br>",
    "- 只有来自<a href=\"https://github.com/laobamac/OCLP-Mod\" style=\"color: #0078D4; text-decoration: none;\">laobamac/OCLP-Mod</a>仓库的OCLP-Mod 3.x.x为macOS Tahoe 26提供了早期补丁支持。<br>": "- Only OCLP-Mod 3.x.x from the <a href=\"https://github.com/laobamac/OCLP-Mod\" style=\"color: #0078D4; text-decoration: none;\">laobamac/OCLP-Mod</a> repository provides early patch support for macOS Tahoe 26.<br>",
    "- 官方的Dortania版本或旧版补丁<b>将无法工作</b>于macOS Tahoe 26。": "- Official Dortania versions or older patches <b>will NOT work</b> on macOS Tahoe 26.",
    "警告": "Warning",
    "虽然SimpleKaruzi显著减少了设置时间，但Hackintosh之旅仍然需要：<br><br>- 理解<a href=\"https://dortania.github.io/OpenCore-Install-Guide/\" style=\"color: #F57C00; text-decoration: none;\">Dortania指南</a>中的基本概念<br>- 在安装过程中进行测试和故障排除<br>- 耐心和坚持解决出现的任何问题<br><br>我们的工具不能保证第一次尝试就能成功安装，但它应该能帮助您开始。": "While SimpleKaruzi significantly reduces setup time, the Hackintosh journey still requires:<br><br>- Understanding basic concepts in the <a href=\"https://dortania.github.io/OpenCore-Install-Guide/\" style=\"color: #F57C00; text-decoration: none;\">Dortania Guide</a><br>- Testing and troubleshooting during installation<br>- Patience and persistence to solve any issues<br><br>Our tool does not guarantee a successful installation on the first try, but it should help you get started.",
    "快速开始": "Quick Start",
    "1. 选择硬件报告": "1. Select Hardware Report",
    "选择你要为其构建 EFI 的目标系统的硬件报告。": "Select the hardware report for the target system you want to build the EFI for.",
    "2. 检查兼容性": "2. Check Compatibility",
    "审查硬件与 macOS 的兼容性。": "Review hardware compatibility with macOS.",
    "3. 配置设置": "3. Configure Settings",
    "自定义 OpenCore EFI 的 ACPI 补丁、驱动（Kexts）和配置。": "Customize ACPI patches, drivers (Kexts), and configuration for OpenCore EFI.",
    "4. 生成 EFI": "4. Generate EFI",
    "生成你的 OpenCore EFI。": "Generate your OpenCore EFI.",
    "选择硬件报告": "Select Hardware Report",
    "选择你要为其构建 EFI 的目标系统的硬件报告": "Select the hardware report for the target system you want to build the EFI for",
    "选择方式": "Selection Method",
    "导入 AIDA64 报告 (HTML)": "Import AIDA64 Report (HTML)",
    "在本机生成报告": "Generate Report Locally",
    "就绪": "Ready",
    "报告概览": "Report Overview",
    "硬件报告加载成功": "Hardware report loaded successfully",
    "正在解析报告...": "Parsing report...",
    "正在生成报告...": "Generating report...",
    "正在读取文件...": "Reading file...",
    "无法解析文件": "Unable to parse file",
    "正在扫描硬件...": "Scanning hardware...",
    "生成报告失败": "Failed to generate report",
    "正在分析硬件配置...": "Analyzing hardware configuration...",
    "完成": "Done",
    "错误: {}": "Error: {}",
    "快速指南": "Quick Guide",
    "<b>Windows 用户：</b>点击 <span style=\"color:#0078D4; font-weight:600;\">导出硬件报告</span> 按钮为当前系统生成硬件报告。或者，您可以使用 Hardware Sniffer 工具手动生成报告。<br>": "<b>Windows Users:</b> Click <span style=\"color:#0078D4; font-weight:600;\">Export Hardware Report</span> button to generate a report for the current system. Or use Hardware Sniffer manually.<br>",
    "<b>Linux/macOS 用户：</b>请传输在 Windows 上生成的报告。不支持本机生成。": "<b>Linux/macOS Users:</b> Please transfer the report generated on Windows. Native generation is not supported.",
    "导出硬件报告": "Export Hardware Report",
    "硬件报告详情": "Hardware Report Details",
    "查看选定的报告路径和验证状态": "View selected report path and validation status",
    "报告路径": "Report Path",
    "ACPI 目录": "ACPI Directory",
    "未选择": "Not Selected",
    "硬件兼容性": "Hardware Compatibility",
    "查看硬件与 macOS 的兼容性": "Check hardware compatibility with macOS",
    "详细信息": "Details",
    "简约视图": "Simple View",
    "加载硬件报告以查看兼容性信息": "Load hardware report to view compatibility information",
    "报告中未找到兼容的硬件信息。": "No compatible hardware information found in the report.",
    "请确保硬件报告包含有效的设备数据。": "Please ensure the hardware report contains valid device data.",
    "未检测到不兼容的硬件": "No incompatible hardware detected",
    "太棒了！您的所有硬件组件（CPU、显卡、网卡等）似乎都兼容 macOS。<br>您可以点击右上角的“详细信息”开关查看完整规格列表。": "Great! All your hardware components (CPU, GPU, Network, etc.) seem compatible with macOS.<br>You can toggle the \"Details\" switch in the top right to view the full specification list.",
    "检测到需要 OCLP 补丁的硬件": "Hardware requiring OCLP patches detected",
    "您的部分硬件在较新版本的 macOS 上需要使用 <b>OCLP(-Mod)</b> 才能正常工作。<br>SimpleKaruzi 将在构建过程中自动协助您配置补丁。": "Some of your hardware requires <b>OCLP(-Mod)</b> to work correctly on newer macOS versions.<br>SimpleKaruzi will automatically assist you in configuring patches during the build process.",
    "硬件兼容性问题": "Hardware Compatibility Issues",
    "缺少必需的 SSE4.x 指令集。": "Missing required SSE4.x instruction set.",
    "您的 CPU 不支持比 Sierra (10.12) 更新的 macOS 版本。": "Your CPU does not support macOS versions newer than Sierra (10.12).",
    "无法在没有受支持 GPU 的情况下安装 macOS。": "Cannot install macOS without a supported GPU.",
    "请不要再就此问题向我发送垃圾邮件或提交 issue！": "Please do not spam me or submit issues about this!",
    "macOS 不支持 Intel VMD 控制器。": "macOS does not support Intel VMD controllers.",
    "请在 BIOS 设置中禁用 Intel VMD，然后重新生成硬件报告并重试。": "Please disable Intel VMD in BIOS settings, then regenerate the hardware report and try again.",
    "未找到兼容 macOS 的存储控制器！": "No macOS-compatible storage controller found!",
    "建议为您的系统购买兼容的 NVMe SSD。": "It is recommended to purchase a compatible NVMe SSD for your system.",
    "原生 macOS 支持：{}": "Native macOS support: {}",
    "\n补丁扩展支持：{}": "\nPatched extended support: {}",
    "硬件兼容": "Hardware Compatible",
    "硬件不兼容": "Hardware Incompatible",
    "未找到支持此硬件配置的 macOS 版本。": "No macOS version found supporting this hardware configuration.",
    "不支持": "Unsupported",
    "最高支持 {}": "Supported up to {}",
    "{} 至 {}": "{} to {}",
    "未知": "Unknown",
    "处理器 (CPU)": "Processor (CPU)",
    "处理器型号": "Processor Model",
    "macOS 兼容性": "macOS Compatibility",
    "代号": "Codename",
    "核心数": "Cores",
    "线程数": "Threads",
    "基础频率": "Base Frequency",
    "显卡 (Graphics)": "Graphics (GPU)",
    "类型: {}": "Type: {}",
    "OCLP 兼容性": "OCLP Compatibility",
    "通过 OCLP(-Mod) 提供扩展支持": "Extended support via OCLP(-Mod)",
    "设备 ID": "Device ID",
    "供应商": "Vendor",
    "已连接显示器": "Connected Monitors",
    " (不支持)": " (Unsupported)",
    "声卡 (Audio)": "Audio (Sound)",
    "控制器 ID": "Controller ID",
    "音频接口": "Audio Endpoints",
    "网卡 (Network)": "Network",
    "接力功能 (Continuity)": "Continuity",
    "完整支持 (隔空投送, 接力, 通用剪贴板, 个人热点等)": "Full Support (AirDrop, Handoff, Universal Clipboard, Personal Hotspot, etc.)",
    "部分支持 (通过 AirportItlwm 实现接力与通用剪贴板) - 隔空投送, 个人热点等不可用": "Partial Support (Handoff & Clipboard via AirportItlwm) - AirDrop, Hotspot unavailable",
    "有限支持 (无接力功能)。不推荐在 macOS 使用 Atheros 网卡。": "Limited Support (No Handoff). Atheros cards are not recommended for macOS.",
    "总线类型": "Bus Type",
    "存储 (Storage)": "Storage",
    "磁盘驱动器": "Disk Drives",
    "蓝牙 (Bluetooth)": "Bluetooth",
    "生物识别 (Biometric)": "Biometric",
    "硬件限制": "Hardware Limitation",
    "macOS 的生物识别验证需要 Apple T2 芯片，黑苹果系统无法支持。": "Biometric authentication in macOS requires Apple T2 chip, which is not supported on Hackintosh.",
    "SD 控制器": "SD Controller",
    "配置": "Configuration",
    "配置您的 OpenCore EFI 设置": "Configure your OpenCore EFI settings",
    "兼容性状态": "Compatibility Status",
    "部分硬件组件已从配置中排除": "Some hardware components are excluded from configuration",
    "请先选择硬件报告": "Please select a hardware report first",
    "请先选择目标 macOS 版本": "Please select a target macOS version first",
    "所有硬件组件均兼容并已启用": "All hardware components are compatible and enabled",
    "不兼容": "Incompatible",
    "已禁用": "Disabled",
    "macOS 版本": "macOS Version",
    "目标操作系统版本": "Target OS Version",
    "选择版本": "Select Version",
    "macOS 版本已更新为 {}": "macOS version updated to {}",
    "配置补丁": "Configure Patches",
    "ACPI 补丁": "ACPI Patches",
    "自定义系统 ACPI 表修改以适配硬件": "Customize system ACPI table modifications to fit hardware",
    "ACPI 补丁配置已更新": "ACPI patch configuration updated",
    "管理 Kexts": "Manage Kexts",
    "内核扩展 (Kexts)": "Kernel Extensions (Kexts)",
    "配置硬件所需的驱动程序": "Configure drivers required for hardware",
    "Kext 配置已更新": "Kext configuration updated",
    "音频布局 ID (Layout ID)": "Audio Layout ID",
    "为您的音频编解码器选择布局 ID": "Select a layout ID for your audio codec",
    "未配置": "Not Configured",
    "配置布局": "Configure Layout",
    "音频布局 ID 已更新为 {}": "Audio layout ID updated to {}",
    "SMBIOS 机型": "SMBIOS Model",
    "为您的系统选择 Mac 机型标识符": "Select a Mac model identifier for your system",
    "配置机型": "Configure Model",
    "SMBIOS 机型已更新为 {}": "SMBIOS model updated to {}",
    "构建 OpenCore EFI": "Build OpenCore EFI",
    "构建准备安装的定制化 OpenCore EFI": "Build customized OpenCore EFI ready for installation",
    "使用前必读": "Read Before Use",
    "在使用生成的 EFI 之前，请务必完成以下步骤：": "Please complete the following steps before using the generated EFI:",
    "1. BIOS/UEFI 设置要求：": "1. BIOS/UEFI Settings Requirements:",
    "{}. USB 端口定制：": "{}. USB Port Customization:",
    "1. 使用 USBToolBox 工具映射 USB 端口<br>2. 将创建的 UTBMap.kext 添加到 EFI{path_sep}OC{path_sep}Kexts 文件夹中并启用<br>3. 从 EFI{path_sep}OC{path_sep}Kexts 文件夹和config.plist中删除 UTBDefault.kext<br>": "1. Map USB ports using USBToolBox<br>2. Add the created UTBMap.kext to EFI{path_sep}OC{path_sep}Kexts folder and enable it<br>3. Remove UTBDefault.kext from EFI{path_sep}OC{path_sep}Kexts folder and config.plist<br>",
    "构建控制": "Build Control",
    "开始构建": "Start Build",
    "构建中...": "Building...",
    "打开结果文件夹": "Open Result Folder",
    "准备构建": "Ready to Build",
    "构建日志": "Build Log",
    "详细的构建过程信息和状态更新": "Detailed build process information and status updates",
    "安装补丁警告": "Patch Installation Warning",
    "1. 通过安装补丁 (OCLP/OCLP-Mod) 允许在新版 macOS 上恢复被放弃的 GPU 和 Broadcom WiFi 支持，并在 macOS Tahoe 26 上启用 AppleHDA。<br>2. OCLP 需要禁用 SIP 以应用自定义内核补丁，这可能会导致系统不稳定、安全风险和更新问题。<br><b><font color=\"{info_color}\">关于 macOS Tahoe 26 的支持：</font></b><br>要修补 macOS Tahoe 26，必须下载 OCLP-Mod 3.1.3 或更新版本，请访问我的仓库：<a href=\"https://github.com/laobamac/OCLP-Mod/releases\">laobamac/OCLP-Mod</a>。<br>官方 Dortania 发布版或旧版补丁<b>将无法</b>在 macOS Tahoe 26 上工作。": "1. Patching (OCLP/OCLP-Mod) allows restoring dropped GPU and Broadcom WiFi support on newer macOS versions, and enabling AppleHDA on macOS Tahoe 26.<br>2. OCLP requires disabling SIP to apply custom kernel patches, which may cause system instability, security risks, and update issues.<br><b><font color=\"{info_color}\">Regarding macOS Tahoe 26 support:</font></b><br>To patch macOS Tahoe 26, you must download OCLP-Mod 3.1.3 or newer from my repository: <a href=\"https://github.com/laobamac/OCLP-Mod/releases\">laobamac/OCLP-Mod</a>.<br>Official Dortania releases or older patches <b>will NOT work</b> on macOS Tahoe 26.",
    "启用 UEFI 模式（禁用 Legacy/CSM 兼容性支持模块）": "Enable UEFI mode (Disable Legacy/CSM Compatibility Support Module)",
    "禁用安全启动 (Secure Boot)": "Disable Secure Boot",
    "启用 Above 4G Decoding": "Enable Above 4G Decoding",
    "禁用 Resizable BAR / Smart Access Memory": "Disable Resizable BAR / Smart Access Memory",
    "准备构建...": "Preparing to build...",
    "正在复制 EFI 基础文件到结果文件夹": "Copying EFI base files to result folder",
    "正在应用 ACPI 补丁": "Applying ACPI patches",
    "正在复制驱动 (Kexts) 并创建 config.plist 快照": "Copying drivers (Kexts) and creating config.plist snapshot",
    "正在生成 config.plist": "Generating config.plist",
    "正在清理未使用的驱动、资源和工具": "Cleaning up unused drivers, resources, and tools",
    "构建成功完成！": "Build completed successfully!",
    "你的 OpenCore EFI 已成功构建！": "Your OpenCore EFI has been successfully built!",
    " 请查阅下方的使用前重要说明。": " Please read the important instructions below before use.",
    "构建 OpenCore EFI 失败": "Failed to build OpenCore EFI",
    "重试构建": "Retry Build",
    "构建过程中发生错误，请检查日志以获取详细信息。": "An error occurred during the build process, please check the log for details.",
    "无法打开结果文件夹：{}": "Unable to open result folder: {}",
    "目录 \"{}\" 不存在。": "Directory \"{}\" does not exist.",
    "错误：文件 {} 不存在。": "Error: File {} does not exist.",
    "[构建] 无法删除文件 {}: {}": "[Build] Unable to delete file {}: {}",
    "{} 完成！": "{} Completed!",
    "处理中": "Processing",
    "步骤 {}/{}": "Step {}/{}",
    "[构建] {} 完成！": "[Build] {} Completed!",
    "[构建] 步骤 {}/{}: {}...": "[Build] Step {}/{}: {}...",
    "设置": "Settings",
    "配置 SimpleKaruzi 首选项": "Configure SimpleKaruzi preferences",
    "构建输出": "Build Output",
    "浏览": "Browse",
    "输出目录": "Output Directory",
    "使用临时目录（默认）": "Use temporary directory (Default)",
    "选择构建输出目录": "Select Build Output Directory",
    "输出目录更新成功": "Output directory updated successfully",
    "SKSP 资源包": "SKSP Resource Package",
    "当前版本: {}": "Current Version: {}",
    "状态: {}": "Status: {}",
    "已安装": "Installed",
    "未安装": "Not Installed",
    "检查更新": "Check for Updates",
    "自动检查更新": "Auto Check for Updates",
    "在软件启动时自动检查资源包更新。": "Automatically check for resource package updates on startup.",
    "检查中...": "Checking...",
    "更新": "Update",
    "发现 SKSP 新版本: {} ({})\n\n是否立即更新？": "SKSP New Version Found: {} ({})\n\nUpdate immediately?",
    "发现新版本": "New Version Found",
    "检查失败": "Check Failed",
    "获取更新信息时出错: {}": "Error fetching update info: {}",
    "已是最新": "Up to date",
    "当前的 SKSP 资源包已是最新版本。": "The current SKSP resource package is up to date.",
    "成功": "Success",
    "SKSP 更新成功！": "SKSP update successful!",
    "失败": "Failed",
    "更新失败: {}": "Update failed: {}",
    "软件更新": "Software Update",
    "启动时检查更新": "Check for updates on startup",
    "启动时自动检查新版本。": "Automatically check for new versions on startup.",
    "检查软件更新": "Check for Software Updates",
    "立即检查 SimpleKaruzi 是否有新版本": "Immediately check if there is a new version of SimpleKaruzi",
    "正在检查...": "Checking...",
    "发现新版本 v{}": "New version v{} found",
    "发现更新": "Update Found",
    "\n<h3>发现新版本 v{version}</h3>\n<p><b>发布日期:</b> {date}</p>\n<hr>\n<b>更新日志:</b><br>\n{changelog}\n<br><br>\n是否立即下载并安装？<br>程序将在下载完成后重启。\n": "\n<h3>New Version Found v{version}</h3>\n<p><b>Release Date:</b> {date}</p>\n<hr>\n<b>Changelog:</b><br>\n{changelog}\n<br><br>\nDownload and install now?<br>The application will restart after download completes.\n",
    "无更新日志": "No changelog",
    "已是最新版本": "Already the latest version",
    "检查完成": "Check Completed",
    "当前已是最新版本！": "You are using the latest version!",
    "更新检查失败": "Update check failed",
    "下载中...": "Downloading...",
    "正在下载更新，请勿关闭...": "Downloading update, please do not close...",
    "更新成功": "Update Successful",
    "新版本下载解压完成。\n\n点击确定后程序将自动重启以完成安装。": "Update downloaded and extracted.\n\nClick OK to restart and complete installation.",
    "更新失败": "Update Failed",
    "错误详情: {}": "Error Details: {}",
    "macOS 版本": "macOS Version",
    "包含测试版 (Beta)": "Include Beta Versions",
    "在版本列表中显示测试版 macOS。": "Show beta macOS versions in the list.",
    "外观": "Appearance",
    "跟随系统": "Follow System",
    "亮色": "Light",
    "暗色": "Dark",
    "语言": "Language",
    "选择应用程序的界面语言。": "Select the application interface language.",
    "需要重启": "Restart Required",
    "语言设置已更改，请重启应用程序以生效。": "Language setting changed. Please restart the application to take effect.",
    "主题": "Theme",
    "选择应用程序的颜色主题。": "Select the application color theme.",
    "高级设置": "Advanced Settings",
    "启用调试日志": "Enable Debug Logging",
    "启用详细日志用于故障排除。": "Enable verbose logging for troubleshooting.",
    "帮助与文档": "Help & Documentation",
    "OpenCore 安装指南": "OpenCore Install Guide",
    "OpenCore 文档": "OpenCore Documentation",
    "安装 macOS 的完整指南": "Complete guide for installing macOS",
    "在 GitHub 上查看": "View on GitHub",
    "SimpleKaruzi 仓库": "SimpleKaruzi Repository",
    "源码与 Issue": "Source Code & Issues",
    "重置设置": "Reset Settings",
    "重置所有设置": "Reset All Settings",
    "确定要重置所有设置吗？": "Are you sure you want to reset all settings?",
    "所有设置已重置": "All settings have been reset",
    "确定": "OK",
    "取消": "Cancel",
    "是": "Yes",
    "否": "No",
    "在此设备上发现了 {} 个 WiFi 网络。<br><br>您想处理多少个网络？<br><ul><li>输入数字 (1-{})</li><li>或选择“处理所有网络”</li></ul>": "{} WiFi networks were found on this device.<br><br>How many networks do you want to process?<br><ul><li>Enter a number (1-{})</li><li>Or select \"Process All Networks\"</li></ul>",
    "WiFi 网络检索": "WiFi Network Retrieval",
    "1-{} (默认: 5)": "1-{} (Default: 5)",
    "处理所有网络": "Process All Networks",
    "显示所有型号": "Show all models",
    "恢复默认 ({})": "Restore Default ({})",
    "类别: {}": "Category: {}",
    "<b style=\"color: #1565C0\">建议的 macOS 版本：</b> 为了更好的兼容性和稳定性，建议您仅使用 <b>{}</b> 或更旧版本。<br><br>": "<b style=\"color: #1565C0\">Suggested macOS Version:</b> For better compatibility and stability, it is recommended to use <b>{}</b> or older.<br><br>",
    "请选择您想要使用的 macOS 版本：": "Please select the macOS version you want to use:",
    " <i style=\"color: #FF8C00\">(需要 OCLP 补丁)</i>": " <i style=\"color: #FF8C00\">(Requires OCLP Patch)</i>",
    "选择 macOS 版本": "Select macOS Version",
    "下载中": "Downloading",
    "正在连接...": "Connecting...",
    "正在取消...": "Cancelling...",
    "STEP {} OF {}": "STEP {} OF {}",
    "发现 SKSP 资源包更新": "SKSP Resource Package Update Found",
    "检测到新版本的 SKSP 资源包 (v{})。<br>发布日期: {}<br><br>{}<br><br>更新资源包可以提高硬件识别准确率和驱动兼容性。<br>是否立即更新？": "A new version of SKSP resource package (v{}) was detected.<br>Release Date: {}<br><br>{}<br><br>Updating the resource package can improve hardware recognition accuracy and driver compatibility.<br>Update now?",
    "立即更新": "Update Now",
    "稍后": "Later",
    "主页": "Home",
    "4. 生成与预览": "4. Build & Preview",
    "提示": "Info",
    "请先加载 ACPI 表": "Please load ACPI table first",
    "检测到不兼容的硬件，请选择其他硬件报告并重试": "Incompatible hardware detected, please select another hardware report and try again",
    "请重新加载硬件报告并选择目标 macOS 版本以继续": "Please reload hardware report and select target macOS version to continue",
    "虽然SimpleKaruzi显著减少了设置时间，但Hackintosh之旅仍然需要：<br><br>": "While SimpleKaruzi significantly reduces setup time, the Hackintosh journey still requires:<br><br>",
    "- 理解<a href=\"https://dortania.github.io/OpenCore-Install-Guide/\" style=\"color: #F57C00; text-decoration: none;\">Dortania指南</a>中的基本概念<br>": "- Understanding basic concepts in the <a href=\"https://dortania.github.io/OpenCore-Install-Guide/\" style=\"color: #F57C00; text-decoration: none;\">Dortania Guide</a><br>",
    "- 在安装过程中进行测试和故障排除<br>": "- Testing and troubleshooting during installation<br>",
    "- 耐心和坚持解决出现的任何问题<br><br>": "- Patience and persistence to solve any issues<br><br>",
    "我们的工具不能保证第一次尝试就能成功安装，但它应该能帮助您开始。": "Our tool does not guarantee a successful installation on the first try, but it should help you get started.",
    "当前版本: v{}": "Current Version: v{}",
    "当前版本: {}": "Current Version: {}",
    "未选择": "Not Selected"
}

def get_context_from_filename(filename):
    if "settings_page.py" in filename: return "SettingsPage"
    if "build_page.py" in filename: return "BuildPage"
    if "home_page.py" in filename: return "HomePage"
    if "compatibility_page.py" in filename: return "CompatibilityPage"
    if "configuration_page.py" in filename: return "ConfigurationPage"
    if "select_hardware_report_page.py" in filename: return "SelectHardwareReportPage"
    if "custom_dialogs.py" in filename: return "CustomDialogs"
    if "ui_utils.py" in filename: return "UIUtils"
    if "SimpleKaruzi.py" in filename: return "OCS"
    return ""

def refine_context(context_name, source_text):
    if context_name == "ConfigurationPage":
        if "音频布局 ID" in source_text or "Audio Layout ID" in source_text: return "AudioLayoutCard"
        if "SMBIOS 机型" in source_text or "SMBIOS Model" in source_text: return "SMBIOSModelCard"
        if "macOS 版本" in source_text or "macOS Version" in source_text: return "macOSCard"
        
    if context_name == "SelectHardwareReportPage":
        if "报告路径" in source_text or "Report Path" in source_text: return "ReportDetailsGroup"
        if "ACPI 目录" in source_text or "ACPI Directory" in source_text: return "ReportDetailsGroup"
        if "未选择" in source_text or "Not Selected" in source_text: return "ReportDetailsGroup" # Added refinement for generic string in this context
        
    return context_name

def translate_ts(ts_path):
    print(f"Processing: {ts_path}")
    
    try:
        tree = ET.parse(ts_path)
        root = tree.getroot()
        
        root.set('language', 'en_US')
        
        new_root = ET.Element("TS", version="2.1", language="en_US")
        
        contexts = {}
        
        all_messages = []
        for context in root.findall('context'):
            all_messages.extend(context.findall('message'))
            
        for message in all_messages:
            location = message.find('location')
            if location is None: continue
            
            filename = location.attrib.get('filename', '')
            context_name = get_context_from_filename(filename)
            
            source_node = message.find('source')
            translation_node = message.find('translation')
            
            source_text = source_node.text if source_node is not None else ""
            
            context_name = refine_context(context_name, source_text)
            
            if context_name not in contexts:
                ctx_node = ET.SubElement(new_root, "context")
                name_node = ET.SubElement(ctx_node, "name")
                name_node.text = context_name
                contexts[context_name] = ctx_node
            
            if source_node is not None:
                source_text = source_node.text
                if source_text in TRANSLATIONS:
                    translation_node.text = TRANSLATIONS[source_text]
                    if 'type' in translation_node.attrib:
                        del translation_node.attrib['type']
                elif source_text and source_text.strip() in TRANSLATIONS:
                     translation_node.text = TRANSLATIONS[source_text.strip()]
                     if 'type' in translation_node.attrib:
                        del translation_node.attrib['type']
            
            contexts[context_name].append(message)
            
        injections = {
            "SMBIOSModelCard": {
                "未配置": "Not Configured",
                "配置机型": "Configure Model",
                "SMBIOS 机型": "SMBIOS Model",
                "为您的系统选择 Mac 机型标识符": "Select a Mac model identifier for your system"
            },
            "AudioLayoutCard": {
                "未配置": "Not Configured",
                "配置布局": "Configure Layout",
                "音频布局 ID (Layout ID)": "Audio Layout ID",
                "为您的音频编解码器选择布局 ID": "Select a layout ID for your audio codec"
            },
            "macOSCard": {
                "未选择": "Not Selected",
                "选择版本": "Select Version",
                "macOS 版本": "macOS Version",
                "目标操作系统版本": "Target OS Version"
            },
            "ReportDetailsGroup": {
                "未选择": "Not Selected",
                "报告路径": "Report Path",
                "ACPI 目录": "ACPI Directory",
                "硬件报告详情": "Hardware Report Details",
                "查看选定的报告路径和验证状态": "View selected report path and validation status"
            }
        }
        
        for ctx_name, msgs in injections.items():
            if ctx_name not in contexts:
                ctx_node = ET.SubElement(new_root, "context")
                name_node = ET.SubElement(ctx_node, "name")
                name_node.text = ctx_name
                contexts[ctx_name] = ctx_node
            
            existing_sources = set()
            for msg in contexts[ctx_name].findall('message'):
                src = msg.find('source')
                if src is not None:
                    existing_sources.add(src.text)
            
            for src_text, trans_text in msgs.items():
                if src_text not in existing_sources:
                    msg_node = ET.SubElement(contexts[ctx_name], "message")
                    src_node = ET.SubElement(msg_node, "source")
                    src_node.text = src_text
                    trans_node = ET.SubElement(msg_node, "translation")
                    trans_node.text = trans_text
        
        new_tree = ET.ElementTree(new_root)
        new_tree.write(ts_path, encoding='utf-8', xml_declaration=True)
        print(f"Successfully restructured and translated {ts_path}")
        
    except Exception as e:
        print(f"Error processing {ts_path}: {e}")

if __name__ == "__main__":
    translate_ts("Translations/en_US.ts")

